name: scrape-ig

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: ["**"]
    # tags: ["**"]
  schedule:
    - cron: 10-59/15 * * * *

env:
  BOT_TOKEN: ${{secrets.BOT_TOKEN}}
  MONGO_URL: ${{secrets.MONGO_URL}}
  REDIS_URL: ${{secrets.REDIS_URL}}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: dipsywong98/mirror-on-wall
          latest: true
          fileName: dist.tar
          tarBall: false
          zipBall: false
          extract: true
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"
      - run: "ls"
      - run: "MODE=scrape-ig node dist/index.js"
