name: toast-classquota

on:
  workflow_dispatch:
    inputs: 
      workflow_file_name:
        type: choice
        description: which workflow file to trigger
        options:
          - toast2.yml
          - toast.yml
        default: toast2.yml
  push:
    branches: ["**"]

jobs:
  toast:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: dipsywong98
        repo: roaster
        github_token: ${{ secrets.TOAST_TOKEN }}
        workflow_file_name: ${{ github.event.inputs.workflow_file_name }}
        client_payload: '{"url": "https://w5.ab.ust.hk/wcq/cgi-bin/2320/", "timeout": "10", "dir": "classquota", "repo-name": "toast-class-quota", "ssh-key": "${{ secrets.TOAST_CLASS_QUOTA_SSH_KEY }}"}'
        ref: master
        wait_workflow: false
