name: toast-classquota

on:
  workflow_dispatch:
    inputs: 
      workflow_file_name:
        type: string
        description: which workflow file to trigger
        default: toast2.yml
      timeout:
        type: number
        description: the timeout for the workflow
        default: 18000
      fresh:
        type: boolean
        description: if true, it will drop all content in toast-cache.sqlite before downloading
        default: false
  # push:
  #   branches: ["**"]

jobs:
  toast:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: dipsywong98
        repo: roaster
        github_token: ${{ secrets.TOAST_TOKEN }}
        workflow_file_name: ${{ github.event.inputs.workflow_file_name || 'toast2.yml' }}
        client_payload: '{"url": "https://w5.ab.ust.hk/wcq/cgi-bin/2320/", "timeout": "${{ github.event.inputs.timeout || 18000 }}", "dir": "classquota", "repo-name": "toast-class-quota", "ssh-key": "TOAST_CLASS_QUOTA_SSH_KEY", "fresh": "${{ github.event.inputs.fresh || false }}"}'
        ref: master
        wait_workflow: false
