name: toast

on:
  workflow_dispatch:
    inputs:
      url:
        description: the url you want to track
      dir:
        description: the dir you store the archive
      repo-user:
        description: username of the owner of the repo that save the archive
        default: dipsywong98
      repo-name:
        description: the name of the repo that save the archive
        default: toast
      timeout:
        description: seconds to pause and check in
        default: "18000"
      ssh-key:
        description: secret name of the ssh key to push to target repo
      fresh:
        description: if true, it will drop all content in toast-cache.sqlite before downloading
        default: "false"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{inputs.repo-user}}/${{inputs.repo-name}}
          path: website
          token: ${{ secrets.TOAST_TOKEN }}
      - uses: robinraju/release-downloader@v1.8
        continue-on-error: true
        with:
          repository: ${{inputs.repo-user}}/${{inputs.repo-name}}
          tag: ${{ inputs.dir }}
          fileName: toast-cache.sqlite
          tarBall: false
          zipBall: false
          extract: false
          token: ${{ secrets.TOAST_TOKEN }}
      - name: download toast
        uses: robinraju/release-downloader@v1.8
        continue-on-error: true
        with:
          repository: dipsywong98/toaster
          latest: true
          fileName: toast.js
          tarBall: false
          zipBall: false
          extract: false
          token: ${{ secrets.TOAST_TOKEN }}
      - run: ls
      - run: ls website
      - run: timeout --foreground --preserve-status -s SIGINT ${{ inputs.timeout }} bun toast.js -u ${{ inputs.url }} -o website --db toast-cache.sqlite --resume --fresh=${{ inputs.fresh }}
      - name: compute zip file name
        id: compute_zip
        run: |
          VALUE="website-$(date +%Y%m%d).zip"
          echo "::set-output name=zip_name::$VALUE"
      - run: ./toast/push.sh ${{ inputs.dir }} website ${{ inputs.repo-user }} ${{ inputs.repo-name }} github.com ycwongal@connect.ust.hk "Dipsy Wong" ${{ inputs.repo-user }} main "Update from ORIGIN_COMMIT" true
        env:
          SSH_DEPLOY_KEY: ${{ secrets[github.event.inputs.ssh-key]}}
      # - uses: cpina/github-action-push-to-another-repository@main
      #   env:
      #     SSH_DEPLOY_KEY: ${{ inputs.ssh-key }}
      #   with:
      #     source-directory: 'website'
      #     destination-github-username: ${{ inputs.repo-user }}
      #     destination-repository-name: ${{ inputs.repo-name }}
      #     target-branch: main
      - uses: ncipollo/release-action@v1
        with:
          artifacts: toast-cache.sqlite
          token: ${{ secrets.TOAST_TOKEN }}
          owner: ${{inputs.repo-user}}
          repo: ${{inputs.repo-name}}
          tag: ${{ inputs.dir }}
          allowUpdates: true
          removeArtifacts: true
          
