name: toast-classquota

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: ["**"]

jobs:
  toast:
    runs-on: ubuntu-latest
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: dipsywong98
        repo: roaster
        github_token: ${{ secrets.TOAST_TOKEN }}
        workflow_file_name: toast.yml
        client_payload: '{"url": "https://w5.ab.ust.hk/wcq/cgi-bin/2320/", "repo": "dipsywong98/toast-classquota"}'
