name: toast

on:
  workflow_dispatch:
    inputs:
      url:
        description: the url you want to track
      repo-user:
        description: username of the owner of the repo that save the archive
      repo-name:
        description: the name of the repo that save the archive

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Install httrack
        run: sudo apt-get install -y httrack
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: ${{inputs.repo-user}}/${{inputs.repo-name}}
          path: website
      - uses: robinraju/release-downloader@v1.8
        continue-on-error: true
        with:
          repository: ${{inputs.repo-user}}/${{inputs.repo-name}}
          latest: true
          fileName: cache-part*
          tarBall: false
          zipBall: false
          extract: false
          token: ${{ secrets.TOAST_TOKEN }}
      - run: ls
      - run: sh toast/copy.sh ${{ inputs.url }}
      - uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOAST_TOKEN }}
        with:
          source-directory: 'website'
          destination-github-username: ${{ inputs.repo-user }}
          destination-repository-name: ${{ inputs.repo-name }}
          target-branch: main
      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist/cache-parts*
          token: ${{ secrets.TOAST_TOKEN }}
          repo: ${{inputs.repo-user}}/${{inputs.repo-name}}
          tag: cache
          allowUpdates: true
          
